In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random

list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_m_arr_1 = np.array(m_list_1)
np.arange(1, 10)

np.linspace(0, 100, 5)
np.zeros(4)
np.zeros((2, 3))

np.ones((2,3))
np_m_arr_1.size
np_arr_2 = np.array([1, 2, 3, 4, 5, 6])

np_arr_2.dtype
np.random.randint(10, 50, 5)
np.random.randint(10, 50, size = (2, 3))

#np.random.randint?

array([[25, 17, 42],
       [39, 42, 35]])

In [2]:
np_m_arr_1
np_m_arr_1.shape
np_m_arr_1[0, 1]

np_m_arr_1.item(0, 1)
np.take(np_m_arr_1, [0, 3, 6])
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])

print(np_m_arr_1)
np_arr_1[:5:2]
np_m_arr_1[:, 1]

np_arr_1[::-1]
evens = np_m_arr_1[np_m_arr_1 % 2 == 0]
evens

np_m_arr_1[np_m_arr_1 > 5]
np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]
np_m_arr_1[(np_m_arr_1 > 5) | (np_m_arr_1 == 10)]

np.unique(np_m_arr_1)

[[10  2  3]
 [10  5  6]
 [10  8  9]]


array([ 2,  3,  5,  6,  8,  9, 10])

In [3]:
np_m_arr_1.reshape((1, 9))
np_m_arr_1
#np_m_arr_1.resize((2,5))

np_m_arr_1
np_m_arr_1.transpose()
np_m_arr_1.swapaxes(0, 1)

np_m_arr_1.flatten()
np_m_arr_1.flatten('F')
np_m_arr_1.sort(axis=0)

print(np_m_arr_1)
np_m_arr_1.sort(axis=0)
print(np_m_arr_1)


[[10  2  3]
 [10  5  6]
 [10  8  9]]
[[10  2  3]
 [10  5  6]
 [10  8  9]]


In [4]:
ss_arr_1 = np.random.randint(10, size=(2, 2))
print('ss_arr_1\n', ss_arr_1)
ss_arr_2 = np.random.randint(10, size=(2, 2))

print('ss_arr_2\n', ss_arr_2)
np.vstack((ss_arr_1, ss_arr_2))
np.hstack((ss_arr_1, ss_arr_2))

ss_arr_3 = np.delete(ss_arr_1, 1, 0)
ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print('ss_arr_3\n', ss_arr_3)

print('ss_arr_4\n', ss_arr_4)
np.column_stack((ss_arr_3, ss_arr_4)) #hstack
np.row_stack((ss_arr_3, ss_arr_4)) #vstack

ss_arr_5 = np.random.randint(10, size=(2, 10))
print('ss_arr_5\n', ss_arr_5)
np.hsplit(ss_arr_5, 5)

np.hsplit(ss_arr_5, (2, 4))
np.vsplit(ss_arr_5, 2)

ss_arr_1
 [[6 7]
 [8 6]]
ss_arr_2
 [[6 8]
 [3 9]]
ss_arr_3
 [[6 7]]
ss_arr_4
 [[6 8]]
ss_arr_5
 [[4 9 6 0 2 4 1 3 0 2]
 [6 8 1 8 0 3 2 9 8 6]]


[array([[4, 9, 6, 0, 2, 4, 1, 3, 0, 2]]),
 array([[6, 8, 1, 8, 0, 3, 2, 9, 8, 6]])]

In [5]:
cp_arr_1 = np.random.randint(10, size=(2, 2))
cp_arr_2 = cp_arr_1
cp_arr_1[0, 0] = 100

print('cp_arr_1\n', cp_arr_1)
print('cp_arr_2\n', cp_arr_2)
cp_arr_3 = cp_arr_1.view()

print('cp_arr_3\n', cp_arr_3)
cp_arr_3 = cp_arr_3.flatten('F')
print('cp_arr_3\n', cp_arr_3)

print('cp_arr_3\n', cp_arr_1)
cp_arr_4 = cp_arr_1.copy()


cp_arr_1
 [[100   7]
 [  2   4]]
cp_arr_2
 [[100   7]
 [  2   4]]
cp_arr_3
 [[100   7]
 [  2   4]]
cp_arr_3
 [100   2   7   4]
cp_arr_3
 [[100   7]
 [  2   4]]


In [6]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
arr_3 + arr_4

arr_3 - arr_4
arr_3 * arr_4
arr_3 / arr_4

arr_5 = random.randint(100, size=(4))
arr_5
arr_6 = random.randint(100, size=(2, 3))

arr_6
random.rand(4)
random.choice(arr_3)

arr_3.sum()
print(arr_6)
arr_6.sum(axis=0) # 0 = columns sum, 1 = row sum

arr_6.cumsum(axis=1)
arr_6.min(axis=1)
arr_6.max(axis=0)

print('arr_3', arr_3)
print('arr_4', arr_4)
np.add(arr_3, 5)

np.add(arr_3, arr_4)
np.subtract(arr_3, arr_4)
np.multiply(arr_3, arr_4)
np.divide(arr_3, arr_4)

arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[2, 4], [6, 9]])
print('arr_5\n', arr_5)

print('arr_6\n', arr_6)
np.remainder(arr_6, arr_5)
np.power(arr_6, arr_5)

np.sqrt(arr_3)
np.cbrt(arr_3)
np.absolute([-1, -2])

np.exp(arr_3)
np.log(arr_3)
np.log2(arr_3)

np.log10(arr_3)
np.gcd.reduce([9, 12, 15])
np.lcm.reduce([9, 12, 15])

np.floor([1.2, 2.5])
np.ceil([1.2, 2.5])
sq_arr = np.arange(6)**2

sq_arr[arr_3]
arr_7 = random.randint(100, size=(5, 3))
print('arr_7\n', arr_7)

mc_index = arr_7.argmax(axis=0)
print(mc_index)
max_nums = arr_7[mc_index]

arr_7[mc_index, range(arr_7.shape[1])] #arr_7[mc_index, 3], find the largest num by the col of the array


[[55 40 98]
 [ 5 38 29]]
arr_3 [1 2 3 4]
arr_4 [2 4 6 8]
arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]
arr_7
 [[84 76 75]
 [50 78 21]
 [23 10 84]
 [48 61 80]
 [86 22 64]]
[4 1 2]


array([86, 78, 84])

In [7]:
import pandas as pd
from numpy import genfromtxt
ic_sales = pd.read_csv('https://raw.githubusercontent.com/derekbanas/NumPy-Tutorial/master/icecreamsales.csv').to_numpy()

ic_sales
ic_sales_2 = genfromtxt('https://raw.githubusercontent.com/derekbanas/NumPy-Tutorial/master/icecreamsales.csv', delimiter=',')
ic_sales_2

ic_sales_2 = [row[~np.isnan(row)] for row in ic_sales_2]
ic_sales_2

[array([], dtype=float64),
 array([ 37., 292.]),
 array([ 40., 228.]),
 array([ 49., 324.]),
 array([ 61., 376.]),
 array([ 72., 440.]),
 array([ 79., 496.]),
 array([ 83., 536.]),
 array([ 81., 556.]),
 array([ 75., 496.]),
 array([ 64., 412.]),
 array([ 53., 324.]),
 array([ 40., 320.])]

In [8]:
sarr_1 = np.arange(1, 6)
np.mean(sarr_1)
np.median(sarr_1)

np.average(sarr_1)
np.std([4, 6, 3, 5, 2])
np.var([4, 6, 3, 5, 2])

print('ic_sales\n', ic_sales)
np.percentile(ic_sales, 50, axis=0)
ic_sales[:, 0]

np.corrcoef(ic_sales[:, 0], ic_sales[:, 1])
temp_mean = np.mean(ic_sales[:, 0])
sales_mean = np.mean(ic_sales[:, 1])

numerator = np.sum(((ic_sales[:, 0] - temp_mean) * (ic_sales[:, 1] - sales_mean)))
denominator = np.sum((np.square(ic_sales[:, 0] - temp_mean)))
slope = numerator / denominator

y_i = sales_mean - slope* temp_mean
y_i
reg_arr = ic_sales[:, 0] * slope + y_i

reg_arr

ic_sales
 [[ 37 292]
 [ 40 228]
 [ 49 324]
 [ 61 376]
 [ 72 440]
 [ 79 496]
 [ 83 536]
 [ 81 556]
 [ 75 496]
 [ 64 412]
 [ 53 324]
 [ 40 320]]


array([256.01208459, 273.8864465 , 327.50953224, 399.00697989,
       464.54630691, 506.25315137, 530.08563392, 518.16939265,
       482.42066882, 416.88134181, 351.34201479, 273.8864465 ])

In [9]:
t_arr = np.linspace(-np.pi, np.pi, 200)
np.arcsin(1)
np.arccos(1)

np.arctan(0)
np.rad2deg(np.pi)
np.deg2rad(180)

np.hypot(10, 10)

14.142135623730951

In [10]:
from numpy import linalg as LA
print('arr_5\n', arr_5)
print('arr_6\n', arr_6)

arr_8 = np.array([[5,6], [7,8]])
np.dot(arr_5, arr_6)
LA.multi_dot([arr_5, arr_6, arr_6])

np.inner(arr_5, arr_6)
np.dot(arr_5, arr_6)
arr_9 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

arr_10 = np.array([[1, 2], [3, 4]], dtype=object)
np.tensordot(arr_9, arr_10)
arr_11 = np.array([0, 1])

arr_12 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
np.einsum('i,ij->i', arr_11, arr_12)
np.einsum('i->', arr_11)

print('arr_3\n', arr_3)
print('arr_4\n', arr_4)
np.einsum('i,i->', arr_3, arr_4)

np.einsum('ij,jk', arr_5, arr_6)
np.einsum('ii', arr_5)
np.einsum('ji', arr_5)

LA.matrix_power(arr_5, 2)
np.kron(arr_5, arr_5)
LA.eig(arr_5)

LA.norm(arr_5)
LA.inv(arr_5)
LA.cond(arr_5)

arr_12 = np.array([[1, 2], [3, 4]])
LA.det(arr_12)
arr_12_i = LA.inv(arr_12)

arr_12_i
np.dot(arr_12, arr_12_i)

arr_13 = np.array([[1, 4], [6, 18]])
arr_14 = np.array([10, 42])
LA.solve(arr_13, arr_14)

np.eye(2, 2, dtype=int)

arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]
arr_3
 [1 2 3 4]
arr_4
 [2 4 6 8]


array([[1, 0],
       [0, 1]])

In [11]:
arr_15 = np.array([[1, 2], [3, 4]])
np.save('randarray', arr_15)
arr_16 = np.load('randarray.npy')

arr_16
np.savetxt('randcsv.csv', arr_15)
arr_17 = np.loadtxt('randcsv.csv')
arr_17

array([[1., 2.],
       [3., 4.]])

In [12]:
!pip install numpy_financial

In [13]:
import numpy_financial as npf
npf.fv(.05/12, 12, -0, -100) # compond interst
period = np.arange(12)+1

principle = 10000.00
ipmt =npf.ipmt(.1/12, period, 12, principle)
ppmt =npf.ppmt(.1/12, period, 12, principle)

for payment in period:
  index = payment-1
  principle = principle + ppmt[index]

  print(f'{payment} {np.round(ppmt[index], 2)} {np.round(ipmt[index], 2)} {np.round(principle, 2)}')

np.round(npf.nper(.1/12, -150, 10000), 2)

npf.npv(0.50, [-15000, 4000, 5000, 6000, 7000]).round(2)

1 -795.83 -83.33 9204.17
2 -802.46 -76.7 8401.72
3 -809.14 -70.01 7592.57
4 -815.89 -63.27 6776.69
5 -822.69 -56.47 5954.0
6 -829.54 -49.62 5124.46
7 -836.46 -42.7 4288.0
8 -843.43 -35.73 3444.58
9 -850.45 -28.7 2594.12
10 -857.54 -21.62 1736.58
11 -864.69 -14.47 871.89
12 -871.89 -7.27 -0.0


-6950.62

In [19]:
carr_1 = np.array([2, 3])
carr_2 = np.array([3, 2])
np.greater(carr_1, carr_2)

np.greater_equal(carr_1, carr_2)
np.less(carr_1, carr_2)
np.less_equal(carr_1, carr_2)

np.not_equal(carr_1, carr_2)
np.equal(carr_1, carr_2)


array([False, False])

NumPy Tutorial : Numpy Full Course: https://www.youtube.com/watch?v=8Y0qQEh7dJg

NumPy Tut: https://github.com/derekbanas/NumPy-Tutorial/blob/master/NumPy%20Tut.ipynb

numpy.linspace: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

numpy.genfromtxt: https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html

numpy-financial documentation fv(future value): https://numpy.org/numpy-financial/latest/fv.html
